version: '3.8'

services:
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube-server
    ports:
      - "9000:9000"
    networks:
      - sonar-net
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    environment:
      - SONAR_FORCEAUTHENTICATION=false
    restart: unless-stopped

networks:
  sonar-net:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
