---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hermes-agent-secret
  namespace: roychshao
spec:
  encryptedData:
    BRAVE_API_KEY: AgCQuPzuqB8+q0t7uR3LLTi4UiXBs4LeU93359BiDRAIYHQdszGjSi/qk0gE+ONRjNDvTl/a3DfXHAyaCEzm8rru5fFUCPcgFmc6A9p/X86aaahtiK2cZOnnutroJ6H9vcV7QyPGriOTOv5fKutUFvzKoMpj6i4Wyqtn9NG5s5UJChWmoIA/HsUnnY6pjq3d1AjGLMy8thZ2KG0YMjiyzA25dChMD4lkB3O+JZSWu2jlqstQmxdlymOQvT6Bu8jbCYkEUvYdxHhQ1j1/+iiLP71F3udbTiuRlwn/C0SmisztSm4V0mm9xu5TwzCsuE06YvTBC4a90zcBXSk6otOu+zdE0qUCAa0j7WGpKbDTBgwI227/rvHWysUwiV8umRP43OCl+OP4f1170Goy5opFtElbq1i8xsKEPAG6kz/gLiFzZrclc06xzxTlq/GmL90T+ySZtf0PVzkcfugkWG9TXAgXcE3pKjRot+tyCpbkCLk3lnJYbqPV7mPioHSeC3XJxAPL+3qXgx4h3A5zEaw4KEFCwua5jRuBUt1Jf+MLrFELY6XLqkWG4E94M5MSl5zcRHnbJjWbbPOQE3QIuCCoN//VQgDi217QgrSFNz0rPTWE+KY8xCPLtG6Dzb8ftWUXWEQgDGWfznbbgsd6LPy3vkTf9EYosqIty7mjwgkAKXqAp71t1Fs+lBsT56bHURxXmTves6gdmZIQSzIHL2q0gi0e7FbA/V7x5qIhUmIe3ft9
    LITE_LLM_API_KEY: AgAnPedaxVpfMA5gCnR0cbztU3ITEH6Y7H6pk/NFPE5uD8MeI7ddD4Uar+eA4rwkxJHZL2wX257/2eNjUZBHMJ4eDTzsTaaqGXyLDoLswxgu4B9P5BWnzGsFDZasGsauapP/Irrnl4arx3f84SJuitIzkmK9yUyMiSN8iGT2dwnBqQ+T1DPWT6Mg2yikvEBs2O7TgjCV4jCGwhh2jxuvbrZphpGs1Y4cBi/Z2y15IZtOMkNED0eO3SGFLmYNNrdj4ytes/oz3y6uUIjl1jKrc4nkng5U0+zPCwoTRf7N4YTZArhvIw5/eG2XkTgq7srM65uK6uawp7Y5MSS1kz6ttvHNdtOHwk4okE3O2t4UOe/vo9fwV9RIliK/jWASY0itnIoeLQno0zR3js81UcSO8Tn74teG+6CUUY7uafxkIm/M6igF0tfIeXkGh2CFqxouih1y/OlIsPVxYa9Sl2EcaaHxJ1s2aoXhQu0SlexjcGM0/gzuBKZsgVpvi44U4xIviOe4yqBGNugA5/4jcGquNMA1IYHVATAJwYIAqH4zJgPoOC+L0oZeycWkCdv3zNS2I7aRa1ByEyZn1Vdi5YAu01kbaJRM2Y2nLMPfy/kglKHA1IyGqrKu539ZC209Tqiow6Ey7nNJGEb+VQBJl7jAuQ9/n63/AjKu69QJ/UXPR9FGwjeRUX1k4rxDk10FeHK+UtdHTFJKbT+hPZhvsW3jxclJXJTDRIXa7gVg
  template:
    metadata:
      name: hermes-agent-secret
      namespace: roychshao
