apiVersion: v1
kind: Service
metadata:
  name: hermes-agent-service
  namespace: roychshao
spec:
  selector:
    app: hermes-agent
  ports:
    - name: agent
      protocol: TCP
      port: 8642
      targetPort: 8642
    - name: dashboard
      protocol: TCP
      port: 9119
      targetPort: 9119
    - name: webui
      protocol: TCP
      port: 8787
      targetPort: 8787
  type: ClusterIP
